services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: airtrend
      POSTGRES_PASS: airtrend
      POSTGRES_DB: airtrend
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
